# Generated by Django 3.2.9 on 2021-11-19 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemStatementCreator',
            fields=[
                ('ps_creator_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=30)),
                ('country', models.CharField(default='India', max_length=30)),
                ('organization_type', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('linked_in', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('nomination_letter', models.FileField(upload_to='problem_statement_creator/nominations')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('first_login', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NodalOfficerNomination',
            fields=[
                ('non_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=30)),
                ('country', models.CharField(default='India', max_length=30)),
                ('organization_type', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('linked_in', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('submitted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problem_statement_creator.problemstatementcreator')),
            ],
        ),
    ]
