# Generated by Django 3.2.9 on 2021-11-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_statement_creator', '0003_alter_nodalofficernomination_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodalofficernomination',
            name='linked_in',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='problemstatementcreator',
            name='linked_in',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
