# Generated by Django 3.2.5 on 2021-11-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_statement_creator', '0004_auto_20211120_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodalofficernomination',
            options={'verbose_name': 'Nominated Nodal Officers', 'verbose_name_plural': 'Nominated Nodal Officers'},
        ),
        migrations.AlterModelOptions(
            name='problemstatementcreator',
            options={'verbose_name': 'Problem Statement Creator', 'verbose_name_plural': 'Problem Statement Creators'},
        ),
        migrations.AlterField(
            model_name='nodalofficernomination',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nodalofficernomination',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nodalofficernomination',
            name='organization',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='problemstatementcreator',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='problemstatementcreator',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='problemstatementcreator',
            name='organization',
            field=models.CharField(max_length=50),
        ),
    ]
