# Generated by Django 3.2.9 on 2021-11-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_statements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemstatementsubmitted',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='problemstatementsubmitted',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
