# Generated by Django 3.2.9 on 2021-11-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_statements', '0004_rename_category_bucket_problemstatementsubmitted_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemstatementsubmitted',
            name='dataset_file',
            field=models.FileField(blank=True, upload_to='problem_statements/dataset/'),
        ),
        migrations.AlterField(
            model_name='problemstatementsubmitted',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
