# Generated by Django 3.2.9 on 2021-12-08 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem_statements', '0005_auto_20211120_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemstatementsubmitted',
            options={'verbose_name': 'Problem Statements Submitted by Problem Statement Creators', 'verbose_name_plural': 'Problem Statements Submitted by Problem Statement Creators'},
        ),
    ]
